[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "deeponet-chem"
version = "0.1.0"
description = "DeepONet chemical network surrogate"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "J. Brennan" }
]
dependencies = [
    "torch",
    "numpy",
    "matplotlib",
]

[project.optional-dependencies]
tune = [
    "optuna>=5.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]